In [21]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import one_hot

In [22]:
## Some Sentences
sent = ['The glass of milk',
        'the glass of Juice',
        'The cup of Tea',
        'I am a Good Boy',
        'I am good Developer',
        'Understand the meaning of words',
        'your videos are good']

In [23]:
sent

['The glass of milk',
 'the glass of Juice',
 'The cup of Tea',
 'I am a Good Boy',
 'I am good Developer',
 'Understand the meaning of words',
 'your videos are good']

In [24]:
## Define the vocalbulary size
voc_size = 10000

In [25]:
sent

['The glass of milk',
 'the glass of Juice',
 'The cup of Tea',
 'I am a Good Boy',
 'I am good Developer',
 'Understand the meaning of words',
 'your videos are good']

In [26]:
## One hot Representation
one_hot_repre = [one_hot(words,voc_size)for words in sent]
one_hot_repre

[[774, 7756, 3672, 9422],
 [774, 7756, 3672, 5138],
 [774, 2469, 3672, 9854],
 [6361, 7372, 551, 5293, 4374],
 [6361, 7372, 5293, 935],
 [6299, 774, 7677, 3672, 8344],
 [9265, 9967, 382, 5293]]

In [27]:
## Word embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [28]:
# Max sentence
sent_length = 8
embedding_docs = pad_sequences(one_hot_repre,padding='pre',maxlen=sent_length)

In [29]:
print(embedding_docs)

[[   0    0    0    0  774 7756 3672 9422]
 [   0    0    0    0  774 7756 3672 5138]
 [   0    0    0    0  774 2469 3672 9854]
 [   0    0    0 6361 7372  551 5293 4374]
 [   0    0    0    0 6361 7372 5293  935]
 [   0    0    0 6299  774 7677 3672 8344]
 [   0    0    0    0 9265 9967  382 5293]]


In [30]:
## Feature Representation
dim = 8

In [31]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [32]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [33]:
model.predict(embedding_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step


array([[[-0.04264235,  0.0276317 ,  0.00793422, -0.00635986,
          0.02465488, -0.02149308,  0.04753308,  0.00706873],
        [-0.04264235,  0.0276317 ,  0.00793422, -0.00635986,
          0.02465488, -0.02149308,  0.04753308,  0.00706873],
        [-0.04264235,  0.0276317 ,  0.00793422, -0.00635986,
          0.02465488, -0.02149308,  0.04753308,  0.00706873],
        [-0.04264235,  0.0276317 ,  0.00793422, -0.00635986,
          0.02465488, -0.02149308,  0.04753308,  0.00706873],
        [ 0.0293878 ,  0.03781507, -0.01071819, -0.04165692,
          0.0308384 ,  0.02703312,  0.04819958,  0.01110151],
        [ 0.01901926,  0.0117792 , -0.04152762,  0.02762059,
         -0.0077065 , -0.04527365,  0.03481301, -0.00748085],
        [-0.00747174, -0.0347922 ,  0.01352707, -0.00225507,
          0.01195916,  0.04577715,  0.04737662, -0.0033278 ],
        [ 0.01764585, -0.01572609, -0.01488013, -0.01355382,
          0.00419275, -0.03019837, -0.02600399,  0.00365454]],

       [[-0.04

In [34]:
from tensorflow.keras.layers import Input
model = Sequential()
model.add(Input(shape=(sent_length,)))  # Define the input shape

In [35]:
## My first sentence
embedding_docs[0]

array([   0,    0,    0,    0,  774, 7756, 3672, 9422], dtype=int32)

In [36]:
a = model.add(Embedding(input_dim=dim, output_dim=128, input_length=sent_length))